# Generated by Django 6.0.2 on 2026-02-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='it_liste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.CharField(max_length=20)),
                ('gruppe', models.CharField(max_length=40)),
                ('beschreibung', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=300)),
                ('hinweise', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='roadmap_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ziel', models.CharField(max_length=80)),
                ('erledigt', models.BooleanField(default=False)),
                ('erledigt_am', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='skripte_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.CharField(max_length=20)),
                ('titel', models.CharField(max_length=40)),
                ('link', models.CharField(max_length=300)),
                ('text_id', models.CharField(max_length=20)),
                ('text', models.TextField()),
            ],
        ),
    ]
